### ISSUE TITLE
Write a nested example with multiple search spaces

### ISSUE THREAD

**Issue by timruhkopf** [automl/hydra-smac-sweeper#7]
To demonstrate its usefulness, it makes sense to write an example that has a more nested real-world structure.
Something along the lines of:

```
model:
  neurons:
    - 100
    - 300
  another_param: 
     some_value: string
     another_value: int
 
optimizer:
  lr: 0.001

```

and then optimize both neurons[0], neurons[1], some_value, another_value, lr.

Since we probably won't want to only have a single search space during our development process, we could also have multiple search spaces as experiments. This probably is a good addition for a tutorial.
