### ISSUE TITLE
Multiprocessing is hanging

### ISSUE THREAD

**Issue by timruhkopf** [automl/hydra-smac-sweeper#9]
**Problem:**
Trying to run my experiments using 12 CPU workers to cover the initial design in one go results in at least one worker opening a new thread / process from the main run. However, none of the results are written out and the run terminates:

```
  "data": [
    [
      [
        1,
        null,
        0,
        1111.111111111111
      ],
      [
        2147483647.0,
        0.0,
        {
          "__enum__": "StatusType.RUNNING"
        },
        0.0,
        0.0,
        null
      ]
    ],
    [
      [
        2,
        null,
        0,
        1111.111111111111
      ],
      [
        2147483647.0,
        0.0,
        {
          "__enum__": "StatusType.RUNNING"
        },
        0.0,
        0.0,
        null
      ]
    ],
    [
      [
        3,
        null,
        0,
        1111.111111111111
      ],
      [
        2147483647.0,
        0.0,
        {
          "__enum__": "StatusType.RUNNING"
        },
        0.0,
        0.0,
        null
      ]
    ],
    [
      [
        4,
        null,
        0,
        1111.111111111111
      ],
      [
        2147483647.0,
        0.0,
        {
          "__enum__": "StatusType.RUNNING"
        },
        0.0,
        0.0,
        null
      ]
    ],
    [
      [
        5,
        null,
        0,
        1111.111111111111
      ],
      [
        2147483647.0,
        0.0,
        {
          "__enum__": "StatusType.RUNNING"
        },
        0.0,
        0.0,
        null
      ]
    ],
    [
      [
        6,
        null,
        0,
        1111.111111111111
      ],
      [
        2147483647.0,
        0.0,
        {
          "__enum__": "StatusType.RUNNING"
        },
        0.0,
        0.0,
        null
      ]
    ],
    [
      [
        7,
        null,
        0,
        1111.111111111111
      ],
      [
        2147483647.0,
        0.0,
        {
          "__enum__": "StatusType.RUNNING"
        },
        0.0,
        0.0,
        null
      ]
    ],
    [
      [
        8,
        null,
        0,
        1111.111111111111
      ],
      [
        2147483647.0,
        0.0,
        {
          "__enum__": "StatusType.RUNNING"
        },
        0.0,
        0.0,
        null
      ]
    ],
    [
      [
        9,
        null,
        0,
        1111.111111111111
      ],
      [
        2147483647.0,
        0.0,
        {
          "__enum__": "StatusType.RUNNING"
        },
        0.0,
        0.0,
        null
      ]
    ],
    [
      [
        10,
        null,
        0,
        1111.111111111111
      ],
      [
        2147483647.0,
        0.0,
        {
          "__enum__": "StatusType.RUNNING"
        },
        0.0,
        0.0,
        null
      ]
    ],
    [
      [
        11,
        null,
        0,
        1111.111111111111
      ],
      [
        2147483647.0,
        0.0,
        {
          "__enum__": "StatusType.RUNNING"
        },
        0.0,
        0.0,
        null
      ]
    ],
    [
      [
        12,
        null,
        0,
        1111.111111111111
      ],
      [
        2147483647.0,
        0.0,
        {
          "__enum__": "StatusType.RUNNING"
        },
        0.0,
        0.0,
        null
      ]
    ],
    [
      [
        13,
        null,
        0,
        1111.111111111111
      ],
      [
        2147483647.0,
        0.0,
        {
          "__enum__": "StatusType.RUNNING"
        },
        0.0,
        0.0,
        null
      ]
    ]
  ],
  "config_origins": {
    "1": "Random initial design.",
    "2": "Random initial design.",
    "3": "Random initial design.",
    "4": "Random initial design.",
    "5": "Random initial design.",
    "6": "Random initial design.",
    "7": "Random initial design.",
    "8": "Random initial design.",
    "9": "Random initial design.",
    "10": "Random initial design.",
    "11": "Random initial design.",
    "12": "Random initial design.",
    "13": "Random Search"
  },
  "configs": {
    "1": {
      "lr": 0.003916449174261764,
      "model.multi_head_dims": 117,
      "model.shared_hidden_dims.0": 150,
      "model.shared_hidden_dims.1": 150
    },
    "2": {
      "lr": 0.010671820864393935,
      "model.multi_head_dims": 281,
      "model.shared_hidden_dims.0": 271,
      "model.shared_hidden_dims.1": 109
    },
    "3": {
      "lr": 0.007381238832487746,
      "model.multi_head_dims": 352,
      "model.shared_hidden_dims.0": 146,
      "model.shared_hidden_dims.1": 304
    },
    "4": {
      "lr": 0.008710434577922916,
      "model.multi_head_dims": 150,
      "model.shared_hidden_dims.0": 152,
      "model.shared_hidden_dims.1": 158
    },
    "5": {
      "lr": 0.03769046495183537,
      "model.multi_head_dims": 245,
      "model.shared_hidden_dims.0": 380,
      "model.shared_hidden_dims.1": 110
    },
    "6": {
      "lr": 0.08743167287239438,
      "model.multi_head_dims": 157,
      "model.shared_hidden_dims.0": 215,
      "model.shared_hidden_dims.1": 158
    },
    "7": {
      "lr": 0.0002422177518749893,
      "model.multi_head_dims": 371,
      "model.shared_hidden_dims.0": 185,
      "model.shared_hidden_dims.1": 305
    },
    "8": {
      "lr": 0.00010113718979245285,
      "model.multi_head_dims": 223,
      "model.shared_hidden_dims.0": 199,
      "model.shared_hidden_dims.1": 205
    },
    "9": {
      "lr": 0.005729348984172219,
      "model.multi_head_dims": 196,
      "model.shared_hidden_dims.0": 367,
      "model.shared_hidden_dims.1": 164
    },
    "10": {
      "lr": 0.0005331777011731644,
      "model.multi_head_dims": 275,
      "model.shared_hidden_dims.0": 114,
      "model.shared_hidden_dims.1": 254
    },
    "11": {
      "lr": 0.00015226533950655628,
      "model.multi_head_dims": 263,
      "model.shared_hidden_dims.0": 223,
      "model.shared_hidden_dims.1": 295
    },
    "12": {
      "lr": 0.0037883558960079785,
      "model.multi_head_dims": 151,
      "model.shared_hidden_dims.0": 126,
      "model.shared_hidden_dims.1": 260
    },
    "13": {
      "lr": 0.0003960468578939801,
      "model.multi_head_dims": 336,
      "model.shared_hidden_dims.0": 117,
      "model.shared_hidden_dims.1": 200
    }
  }
  ```
  
  **Setup:**
be aware, that the list expansion (https://github.com/automl-private/hydra-smac-sweeper/issues/6) is quick fixed
  
```
# @package _global_

defaults:
  #  - override /training: ensemble
  - override /hydra/sweeper: SMAC  # be carefull to make it /hydra
  - override /hydra/launcher: submitit_smac_slurm


model:
  n_fidelities: 4  # fixme: the length should automatically adjusted to dataset.slices!
  join: wavg
  shared_hidden_dims:
    - 200
    - 200
  fc_dim:
    - 58 # explicit fixture

training:
  epochs:
    - 200 # pretraining I (multihead-only)
    - 0  # pretraining II (final-head-only)
    - 10000 # full training budget (will be overridden by sweeper)

lr: 0.001


min_epochs: 400

wandb:
  group: smac_rankmlp_freeze
  notes: 'Running the freeze training procedure for optimizing the multiheads and determine AVG vs WAVG'
  mode: 'online'

hydra:
  sweeper:
    budget_variable: training.epochs.2
    seed: ${seed}
    n_jobs: 12

    scenario:
      run_obj: quality
      deterministic: true
      runcount_limit: 50
      cutoff: 1800 # runtime limit for target algorithm
      memory_limit: 3072 # adapt this to reasonable value for your hardware

    intensifier_kwargs:
      initial_budget: ${min_epochs}
      max_budget: ${training.epochs.2}
      eta: 3

    search_space:
      hyperparameters:
        model.shared_hidden_dims.0:
          type: uniform_int
          lower: 100
          upper: 400
          log: true
          default: ${model.shared_hidden_dims.0}
        model.shared_hidden_dims.1:
          type: uniform_int
          lower: 100
          upper: 400
          log: true
          default: ${model.shared_hidden_dims.1}
        model.multi_head_dims:
          type: uniform_int
          lower: 100
          upper: 400
          log: true
          default: ${model.multi_head_dims.0}
    
     launcher:
        partition: cpu_normal

  

  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}

```
